# Generated by Django 5.0.6 on 2026-01-23 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='heaven_project_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=8)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=400)),
                ('real_time_information', models.CharField(max_length=400)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Review_FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=1)),
                ('review', models.CharField(max_length=400)),
                ('foodbank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.food_banks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=400)),
                ('real_time_information', models.CharField(max_length=400)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=1)),
                ('review', models.CharField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.shelters')),
            ],
        ),
        migrations.CreateModel(
            name='Support_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=400)),
                ('real_time_information', models.CharField(max_length=400)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Support_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=1)),
                ('review', models.CharField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heaven_project_app.support_services')),
            ],
        ),
    ]
