# Generated by Django 5.0.6 on 2026-01-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_banks',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_banks', to='heaven_project_app.city'),
        ),
        migrations.AddField(
            model_name='food_banks',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_banks', to='heaven_project_app.country'),
        ),
        migrations.AddField(
            model_name='food_banks',
            name='post_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='shelters',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='heaven_project_app.city'),
        ),
        migrations.AddField(
            model_name='shelters',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='heaven_project_app.country'),
        ),
        migrations.AddField(
            model_name='shelters',
            name='post_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='support_services',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_services', to='heaven_project_app.city'),
        ),
        migrations.AddField(
            model_name='support_services',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_services', to='heaven_project_app.country'),
        ),
        migrations.AddField(
            model_name='support_services',
            name='post_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
