# Generated by Django 5.0.6 on 2026-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0002_food_banks_city_food_banks_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_banks',
            name='opening_times',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='shelters',
            name='opening_times',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='support_services',
            name='opening_times',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
