# Generated by Django 5.0.6 on 2026-01-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0003_food_banks_opening_times_shelters_opening_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_banks',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shelters',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='support_services',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
