# Generated by Django 5.0.6 on 2026-01-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0004_food_banks_category_shelters_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_banks',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='shelters',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='support_services',
            name='location_id',
        ),
    ]
