# Generated by Django 5.0.6 on 2026-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0005_remove_food_banks_location_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_foodbank',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review_shelter',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review_support_service',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='rating',
            field=models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20),
        ),
    ]
