# Generated by Django 5.0.6 on 2026-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
