# Generated by Django 5.0.6 on 2026-03-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0010_food_banks_latitude_food_banks_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_banks',
            old_name='post_code',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='shelters',
            old_name='post_code',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='support_services',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
