# Generated by Django 5.0.6 on 2026-04-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0011_rename_post_code_food_banks_postcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_foodbank',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review_shelter',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review_shelter',
            name='review',
        ),
        migrations.AddField(
            model_name='review_foodbank',
            name='easy_access_q',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review_foodbank',
            name='recommend_q',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review_foodbank',
            name='staff_q',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
