# Generated by Django 5.0.6 on 2026-04-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0012_remove_review_foodbank_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_foodbank',
            name='easy_access_q',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='recommend_q',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='staff_q',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
