# Generated by Django 5.0.6 on 2026-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0013_alter_review_foodbank_easy_access_q_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_banks',
            name='real_time_information',
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='easy_access_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='recommend_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='staff_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
