# Generated by Django 5.0.6 on 2026-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven_project_app', '0014_remove_food_banks_real_time_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_support_service',
            name='review',
        ),
        migrations.AddField(
            model_name='review_shelter',
            name='easy_access_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='review_shelter',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review_shelter',
            name='recommend_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='review_shelter',
            name='staff_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='review_support_service',
            name='easy_access_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='review_support_service',
            name='recommend_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='review_support_service',
            name='staff_q',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='review_foodbank',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review_support_service',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20, null=True),
        ),
    ]
